import numpy as np
import matplotlib.pyplot as plt
import eqocean as eo

def print_varnames(ax, x, dx=0.5, ffact=10):
    """
    Translates print_varnames from R. Plots column headers for the variables.
    """
    varnames = ["q0", "q2", "q4", "h", f"{ffact} x f"]
    nc = len(varnames)
    
    # Set rigid limits to prevent text from drifting
    ax.set_xlim(0, nc * (2 * np.pi + dx) - dx)
    ax.set_ylim(0, 1)
    
    x_shift = x.copy()
    for v in varnames:
        ax.text(np.mean(x_shift), 0.5, v, ha='center', va='center', fontsize=11)
        x_shift = x_shift + 2 * np.pi + dx
        
    ax.axis('off')

def plot_waves_row(ax, x, q0, q2, q4, f, n, dx=0.5, ffact=10, add=False):
    """
    Translates plot_waves_row from R. Plots a single row (time step) of variables.
    """
    h = eo.calc_h(q0, q2, q4)
    ymat = [q0, q2, q4, h, ffact * f]
    nc = len(ymat)
    
    if not add:
        # Constrain window x-axis to prevent it from drawing too long horizontally
        ax.set_xlim(0, nc * (2 * np.pi + dx) - dx)
        ymin, ymax = np.min(ymat), np.max(ymat)
        
        # Handle zero-variance edge cases for the y-axis scaling
        if ymin == ymax:
            ax.set_ylim(ymin - 1, ymax + 1)
        else:
            ax.set_ylim(ymin, ymax)
            
    fmt = 'r--' if add else 'k-'
    
    x_shift = x.copy()
    for j in range(nc):
        # Match R logic: do not plot forcing (j == nc - 1) at the initial step (n == 0)
        if (n > 0) or (j < nc - 1):
            ax.plot(x_shift, ymat[j], fmt, linewidth=1)
            
            # Draw horizontal axis line once per variable block (only on base plot)
            if not add:
                ax.plot([x_shift[0], x_shift[-1]], [0, 0], 'k-', linewidth=0.5)
            
        x_shift = x_shift + 2 * np.pi + dx
        
    if not add:
        # Print the time step label to the left of the row
        ax.text(-0.3, 0, str(n), ha='right', va='center', fontsize=9)
        ax.axis('off')

def plot_waves(x, hist, thist=None):
    """
    Translates plot_waves from R. Sets up the plot region and loops through time steps.
    """
    tmax = hist['q0'].shape[0]
    
    # Fix for "window is too long": Highly constrain the vertical figsize to 6 inches
    fig, axes = plt.subplots(nrows=tmax + 2, ncols=1, figsize=(8, 6))
    
    print_varnames(axes[0], x)
    
    # Loop backwards down to 0, exactly matching (n in tmax:1)
    for idx, n in enumerate(range(tmax - 1, -1, -1)):
        ax = axes[idx + 1]
        
        # Plot model history state (add=False produces black solid lines)
        plot_waves_row(
            ax, x, 
            hist['q0'][n, :], hist['q2'][n, :], hist['q4'][n, :], hist['f'][n, :], 
            n, add=False
        )
        
        # Overlay true state history if provided (add=True produces red broken lines)
        if thist is not None:
            plot_waves_row(
                ax, x, 
                thist['q0'][n, :], thist['q2'][n, :], thist['q4'][n, :], thist['f'][n, :], 
                n, add=True
            )
            
    # Hide the final unused axis generated by the `tmax + 2` grid
    axes[-1].axis('off')
    
    # Remove padding between rows so they pack nicely
    plt.subplots_adjust(hspace=0, wspace=0)
    plt.show()
